#theme: jekyll-theme-minimalistic
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Cultures in AI/AI in Culture
description: Cultures in AI/AI in Culture: A NeurIPS 2022 Workshop
email: aicultures2022@gmail.com
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
  - jemoji
