theme: jekyll-theme-tactile
title: Cultures in AI/AI in Culture
description: Cultures in AI/AI in Culture: A NeurIPS 2022 Workshop
email: aicultures2022@gmail.com
favicon: true

plugins:
  - jekyll-sitemap
  - jemoji
